### ISSUE TITLE
line error when open the Eden editor

### ISSUE THREAD

**Issue by seoge87** [VurtualRuler98/BoxLoader#2]
error missing ]
file\boxloader\functions\fn_driveon.sqf [boxloader_fnc_driveon], line 1

**Comment by serialtasted** [comment]
Error in expression <em","",[""]],["_basic",false,[false]],[_"retrofit","",[""]]]; 
if (isNull _veh |>
 Error position: <"retrofit","",[""]]]; 
if (isNull _veh |>
 Error Missing ]
File \boxloader\functions\fn_driveon.sqf [boxloader_fnc_driveon], line 1

**Comment by VurtualRuler98** [comment]
Pushed an update that should fix this, it was a simple typo.
