### ISSUE TITLE
Script only for Vanilla

### ISSUE THREAD

**Issue by john681611** [VurtualRuler98/BoxLoader#4]
This looks really cool is there any way I could extract the script parts out to just be a script for Vanilla? I want to try and replace R3F logistics

**Comment by VurtualRuler98** [comment]
Vanilla vehicles don't have any VIV carrier space on them, I used invisible custom objects with models to substitute, which isn't possible in a script-only version. fn_addaction in the core addon has the load/unload scripts, though they're extremely barebones(it's just the setVehicleCargo script command).

**Comment by john681611** [comment]
ok
